language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hanno@hannosch.eu
    - pycassa.maintainer@gmail.com

services:
    - cassandra

install:
    - python setup.py develop

script:
    - nosetests -v
